# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
require "open-uri"
Offer.destroy_all
User.destroy_all
Review.destroy_all

file20 = URI.open("https://images.unsplash.com/photo-1479936343636-73cdc5aae0c3?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=580&q=80")
file21 = URI.open("https://images.unsplash.com/photo-1552374196-c4e7ffc6e126?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80")

user1 = User.create(first_name: "Jean", last_name: "Dupont", email: "jean@gmail.com", password: "aaaaaa", guide: true, city: "Marseille" )
user2 = User.create(first_name: "Axel", last_name: "Martin", email: "axel@gmail.com", password: "aaaaaa", guide: true, city: "Paris")
user2.photo.attach(io: file21, filename: 'bar.png', content_type: 'image/png')
user3 = User.create(first_name: "Arthur", last_name: "Bernard", email: "arthur@gmail.com", password: "aaaaaa", guide: true, city: "Marseille")
user4 = User.create(first_name: "Evan", last_name: "Thomas", email: "evan@gmail.com", password: "aaaaaa", guide: true, city: "Marseille")
user5 = User.create(first_name: "Antoine", last_name: "Richard", email: "antoine@gmail.com", password: "aaaaaa", guide: true, city: "Marseille")
user6 = User.create(first_name: "Adam", last_name: "Durand", email: "adam@gmail.com", password: "aaaaaa", guide: true, city: "Paris")
user7 = User.create(first_name: "Alexandre", last_name: "Dubois", email: "alexandre@gmail.com", password: "aaaaaa", guide: true, city: "Paris")
user8 = User.create(first_name: "Carmen", last_name: "Garcia", email: "carmen@gmail.com", password: "aaaaaa", guide: true, city: "Paris")
user9 = User.create(first_name: "Cesar", last_name: "Blanc", email: "cesar@gmail.com", password: "aaaaaa", guide: true, city: "Paris")
user10 = User.create(first_name: "Clara", last_name: "Serra", email: "clara@gmail.com", password: "aaaaaa", guide: true, city: "Paris")
user10.photo.attach(io: file20, filename: 'bar.png', content_type: 'image/png')
user11 = User.create(first_name: "Celine", last_name: "Guisset", email: "celine@gmail.com", password: "aaaaaa", guide: true, city: "Bordeaux")
user12 = User.create(first_name: "Baptiste", last_name: "Mas", email: "baptiste@gmail.com", password: "aaaaaa", guide: true, city: "Bordeaux")
user13 = User.create(first_name: "Brian", last_name: "Pla", email: "brian@gmail.com", password: "aaaaaa", guide: true, city: "Bordeaux")
user14 = User.create(first_name: "Caroline", last_name: "Sola", email: "caroline@gmail.com", password: "aaaaaa", guide: true, city: "Bordeaux")
user15 = User.create(first_name: "Sarah", last_name: "Lopez", email: "sarah@gmail.com", password: "aaaaaa", guide: true, city: "Lyon")
user16 = User.create(first_name: "Benoit", last_name: "Torrès", email: "benoit@gmail.com", password: "aaaaaa", guide: true, city: "Lyon")
user17 = User.create(first_name: "Jules", last_name: "Gil", email: "jules@gmail.com", password: "aaaaaa", guide: true, city: "Lyon")
user18 = User.create(first_name: "Thomas", last_name: "Salvat", email: "thomas@gmail.com", password: "aaaaaa", guide: true, city: "Lyon")
user19 = User.create(first_name: "Audrey", last_name: "Simon", email: "audrey@gmail.com", password: "aaaaaa", guide: true, city: "Lyon")
user20 = User.create(first_name: "Julia", last_name: "Sanchez", email: "julia@gmail.com", password: "aaaaaa", guide: true, city: "Brest")
user21 = User.create(first_name: "Adrien", last_name: "Petit", email: "adrien@gmail.com", password: "aaaaaa", guide: true, city: "Brest")
user22 = User.create(first_name: "Alexis", last_name: "Robert", email: "alexis@gmail.com", password: "aaaaaa", guide: true, city: "Brest")
user23 = User.create(first_name: "Ibrahim", last_name: "Thouvenin", email: "ibrahim@gmail.com", password: "aaaaaa", guide: true, city: "Brest")
user24 = User.create(first_name: "Alexis", last_name: "Robert", email: "alexis@gmail.com", password: "aaaaaa", guide: true, city: "Brest")
user25 = User.create(first_name: "Ibrahim", last_name: "Thouvenin", email: "ibrahim@gmail.com", password: "aaaaaa", guide: true, city: "Rennes")
user26 = User.create(first_name: "Juliette", last_name: "Montagne", email: "juliette@gmail.com", password: "aaaaaa", guide: true, city: "Rennes")
user27 = User.create(first_name: "Laurent", last_name: "Moreau", email: "laurent@gmail.com", password: "aaaaaa", guide: true, city: "Rennes")
user28 = User.create(first_name: "Gilles", last_name: "Moreau", email: "gilles@gmail.com", password: "aaaaaa", guide: true, city: "Nantes")
user29 = User.create(first_name: "Gabriel", last_name: "Navet", email: "gabriel@gmail.com", password: "aaaaaa", guide: true, city: "Nantes")
user30 = User.create(first_name: "Sohan", last_name: "Lefevbre", email: "sohan@gmail.com", password: "aaaaaa", guide: true, city: "Angers")
user31 = User.create(first_name: "Lucas", last_name: "Leroy", email: "lucas@gmail.com", password: "aaaaaa", guide: true, city: "Angers")
user32 = User.create(first_name: "Léo", last_name: "Roux", email: "leo@gmail.com", password: "aaaaaa", guide: true, city: "Angers")
user33 = User.create(first_name: "Gaspard", last_name: "Martin", email: "gaspard@gmail.com", password: "aaaaaa", guide: true, city: "Dijon")
user34 = User.create(first_name: "Maxence", last_name: "Morel", email: "maxence@gmail.com", password: "aaaaaa", guide: true, city: "Dijon")
user35 = User.create(first_name: "Sophie", last_name: "Fournier", email: "sophie@gmail.com", password: "aaaaaa", guide: true, city: "Dijon")
user36 = User.create(first_name: "Kais", last_name: "petit", email: "kais@gmail.com", password: "aaaaaa", guide: true, city: "Dijon")
user37 = User.create(first_name: "Soan", last_name: "Salla", email: "soan@gmail.com", password: "aaaaaa", guide: true, city: "Annecy")
user38 = User.create(first_name: "Come", last_name: "Givre", email: "come@gmail.com", password: "aaaaaa", guide: true, city: "Annecy")
user39 = User.create(first_name: "Evan", last_name: "Flocon", email: "evan@gmail.com", password: "aaaaaa", guide: true, city: "Annecy")
user40 = User.create(first_name: "Maxime", last_name: "Durant", email: "maxime@gmail.com", password: "aaaaaa", guide: true, city: "Annecy")
User.create(first_name: "Camille", last_name: "Poirier", email: "camille@gmail.com", password: "aaaaaa", guide: true, city: "Annecy")
User.create(first_name: "Tom", last_name: "De saxe", email: "tom@gmail.com", password: "aaaaaa", guide: true, city: "Annecy")
User.create(first_name: "Léon", last_name: "Girard", email: "leon@gmail.com", password: "aaaaaa", guide: true, city: "Lille")
User.create(first_name: "Tiago", last_name: "Mulot", email: "tiago@gmail.com", password: "aaaaaa", guide: true, city: "Lille")
User.create(first_name: "Pablo", last_name: "Fontaine", email: "pablo@gmail.com", password: "aaaaaa", guide: true, city: "Lille")
User.create(first_name: "Léandre", last_name: "Lambert", email: "leandre@gmail.com", password: "aaaaaa", guide: true, city: "Lille")
User.create(first_name: "Naim", last_name: "Berry", email: "naim@gmail.com", password: "aaaaaa", guide: true, city: "Lille")
User.create(first_name: "Joseph", last_name: "Leroux", email: "joseph@gmail.com", password: "aaaaaa", guide: true, city: "Lille")
User.create(first_name: "Oscar", last_name: "Choux", email: "oscar@gmail.com", password: "aaaaaa", guide: true, city: "Lille")
User.create(first_name: "Noa", last_name: "Orange", email: "noa@gmail.com", password: "aaaaaa", guide: true, city: "Toulouse")
User.create(first_name: "Elio", last_name: "Richard", email: "elio@gmail.com", password: "aaaaaa", guide: true, city: "Toulouse")
User.create(first_name: "Marius", last_name: "Esposito", email: "marius@gmail.com", password: "aaaaaa", guide: true, city: "Toulouse")
User.create(first_name: "Victor", last_name: "Vignet", email: "victor@gmail.com", password: "aaaaaa", guide: true, city: "Toulouse")
User.create(first_name: "Nael", last_name: "Bedu", email: "nael@gmail.com", password: "aaaaaa", guide: true, city: "Toulouse")
User.create(first_name: "Mathis", last_name: "Farges", email: "mathis@gmail.com", password: "aaaaaa", guide: true, city: "Toulouse")
User.create(first_name: "Fabien", last_name: "Leca", email: "fabien@gmail.com", password: "aaaaaa", guide: true, city: "Toulouse")
User.create(first_name: "Lou", last_name: "Santani", email: "lou@gmail.com", password: "aaaaaa", guide: true, city: "Toulouse")
User.create(first_name: "Louane", last_name: "Blache", email: "louane@gmail.com", password: "aaaaaa", guide: true, city: "Montpellier")
User.create(first_name: "Laure", last_name: "Delamare", email: "laure@gmail.com", password: "aaaaaa", guide: true, city: "Montpellier")
User.create(first_name: "Claire", last_name: "Leglise", email: "claire@gmail.com", password: "aaaaaa", guide: true, city: "Montpellier")
User.create(first_name: "Emilie", last_name: "Rouanet", email: "emilie@gmail.com", password: "aaaaaa", guide: true, city: "Montpellier")
User.create(first_name: "Diego", last_name: "Lefevbre", email: "diego@hotmail.fr", password: "aaaaaa", guide: true, city: "Montpellier")
User.create(first_name: "Livio", last_name: "Roux", email: "livio@hotmail.fr", password: "aaaaaa", guide: true, city: "Montpellier")
User.create(first_name: "Charles", last_name: "Dupond", email: "charles@hotmail.fr", password: "aaaaaa", guide: true, city: "Montpellier")
User.create(first_name: "Samuel", last_name: "Montagne", email: "samuel@hotmail.fr", password: "aaaaaa", guide: true, city: "Montpellier")
User.create(first_name: "Julie", last_name: "Blanche", email: "julie@hotmail.fr", password: "aaaaaa", guide: true, city: "Starsbourg")
User.create(first_name: "Loan", last_name: "Leglise", email: "loan@hotmail.fr", password: "aaaaaa", guide: true, city: "Starsbourg")
User.create(first_name: "Mathieu", last_name: "Santani", email: "mathieu@hotmail.fr", password: "aaaaaa", guide: true, city: "Starsbourg")
User.create(first_name: "Bruno", last_name: "Esposito", email: "bruno@hotmail.fr", password: "aaaaaa", guide: true, city: "Starsbourg")
User.create(first_name: "Benjamin", last_name: "Guillot", email: "benjamin@hotmail.fr", password: "aaaaaa", guide: true, city: "Starsbourg")
User.create(first_name: "Julien", last_name: "Jouanneaux", email: "julien@hotmail.fr", password: "aaaaaa", guide: true, city: "Starsbourg")
User.create(first_name: "Erika", last_name: "Guillot", email: "erika@hotmail.fr", password: "aaaaaa", guide: true, city: "Starsbourg")
User.create(first_name: "Jessica", last_name: "Depouy", email: "jessica@hotmail.fr", password: "aaaaaa", guide: true, city: "Starsbourg")
User.create(first_name: "Isabelle", last_name: "Saby", email: "isabelle@hotmail.fr", password: "aaaaaa", guide: true, city: "Starsbourg")
User.create(first_name: "Virginie", last_name: "Pomme", email: "virginie@hotmail.fr", password: "aaaaaa", guide: true, city: "Toulon")
User.create(first_name: "Paul", last_name: "Vigneau", email: "paul@hotmail.fr", password: "aaaaaa", guide: true, city: "Toulon")
User.create(first_name: "Marie-Paule", last_name: "Bouttier", email: "mariepaulee@hotmail.fr", password: "aaaaaa", guide: true, city: "Toulon")
User.create(first_name: "Jacques", last_name: "Tixier", email: "jacques@hotmail.fr", password: "aaaaaa", guide: true, city: "Toulon")
User.create(first_name: "Mirelle", last_name: "Albouy", email: "mirelle@hotmail.fr", password: "aaaaaa", guide: true, city: "Toulon")
User.create(first_name: "Olivia", last_name: "Madelaine", email: "olivia@hotmail.fr", password: "aaaaaa", guide: true, city: "Toulon")
User.create(first_name: "Bernard", last_name: "Pomme", email: "bernard@hotmail.fr", password: "aaaaaa", guide: true, city: "Toulon")
User.create(first_name: "Pierre", last_name: "Ramirez", email: "pierre@hotmail.fr", password: "aaaaaa", guide: true, city: "Toulon")
User.create(first_name: "Henry", last_name: "Lopez", email: "henry@hotmail.fr", password: "aaaaaa", guide: true, city: "Nice")
User.create(first_name: "François", last_name: "Santiago", email: "francois@hotmail.fr", password: "aaaaaa", guide: true, city: "Nice")
User.create(first_name: "Françoise", last_name: "Ramirez", email: "francoise@hotmail.fr", password: "aaaaaa", guide: true, city: "Nice")
User.create(first_name: "Claire", last_name: "Madelaine", email: "claire@hotmail.fr", password: "aaaaaa", guide: true, city: "Nice")
User.create(first_name: "Lilia", last_name: "Albouy", email: "lilia@hotmail.fr", password: "aaaaaa", guide: true, city: "Nice")
User.create(first_name: "Livia", last_name: "Lignon", email: "livia@hotmail.fr", password: "aaaaaa", guide: true, city: "Nice")
User.create(first_name: "Laura", last_name: "Reina", email: "laura@hotmail.fr", password: "aaaaaa", guide: true, city: "Cannes")
User.create(first_name: "Léa", last_name: "Garcia", email: "lea@hotmail.fr", password: "aaaaaa", guide: true, city: "Cannes")
User.create(first_name: "Louis", last_name: "Albouy", email: "louis@hotmail.fr", password: "aaaaaa", guide: true, city: "Cannes")
User.create(first_name: "Michel", last_name: "DUrand", email: "michel@hotmail.fr", password: "aaaaaa", guide: true, city: "Cannes")
User.create(first_name: "Théo", last_name: "Richard", email: "theo@hotmail.fr", password: "aaaaaa", guide: true, city: "Cannes")
user = User.create(first_name: "Hubert", last_name: "Thomas", email: "hubert@hotmail.fr", password: "aaaaaa", guide: true, city: "Cannes")


# Offer.create(price: 35, theme: "Gastronomie", theme_description: "Découvrez les spécialités culinaires de la ville !", city: "Marseille", user: user1, title: "Journée bouillabaisse", placenumber: 8, hours: 1)
# Offer.create(price: 20, theme: "Gastronomie", theme_description: "Découvrez les spécialités culinaires de la ville !", city: "Marseille", user: user2, title: "Dégustation de spécialité Marseillaise", placenumber: 10)
# Offer.create(price: 40, theme: "Gastronomie", theme_description: "Découvrez les spécialités culinaires de la ville !", city: "Marseille", user: user3, title: "Dégustation gourmande des navettes", placenumber: 12)
# Offer.create(price: 20, theme: "Gastronomie", theme_description: "Découvrez les spécialités culinaires de la ville !", city: "Toulouse", user: user4, title: "Dégustation de Cassoulet", placenumber: 10)
# Offer.create(price: 25, theme: "Gastronomie", theme_description: "Découvrez les spécialités culinaires de la ville !", city: "Toulouse", user: user5, title: "Dégustation Saucisse de Toulouse", placenumber: 11)
# Offer.create(price: 10, theme: "Gastronomie", theme_description: "Découvrez les spécialités culinaires de la ville !", city: "Toulouse", user: user6, title: "Découverte de L'alicuit de canard", placenumber: 8)
# Offer.create(price: 15, theme: "Gastronomie", theme_description: "Découvrez les spécialités culinaires de la ville !", city: "Toulouse", user: user7, title: "Dégustation autour de la violette", placenumber: 14)
# Offer.create(price: 10, theme: "Balade", theme_description: "Venez vous promener dans ville accompagné de votre guide !", city: "Paris", user: user8, title: "Découvrez Paris en balade ", placenumber: 8)
# Offer.create(price: 8, theme: "Balade", theme_description: "Venez vous promener dans ville accompagné de votre guide !", city: "Paris", user: user9, title: "Découvrez les quais de Seine", placenumber: 12)
# Offer.create(price: 12, theme: "Balade", theme_description: "Venez vous promener dans ville accompagné de votre guide !", city: "Paris", user: user10, title: "Visite du Tracadero", placenumber: 8)
# Offer.create(price: 15, theme: "Balade", theme_description: "Venez vous promener dans ville accompagné de votre guide !", city: "Toulouse", user: user11, title: "Viens visiter la ville Rose !", placenumber: 11)
# Offer.create(price: 6, theme: "Balade", theme_description: "Venez vous promener dans ville accompagné de votre guide !", city: "Toulouse", user: user12, title: "Découvre les incontournables de Toulouse !", placenumber: 10)

file = URI.open('https://images.unsplash.com/photo-1566417713940-fe7c737a9ef2?ixlib=rb-1.2.1&ixid=MnwxM[%E2%80%A6]G90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=829&q=80')

file2 = URI.open("https://i.pinimg.com/564x/5c/2e/da/5c2eda34c6587c5780422c3591b9db58.jpg")
file3 = URI.open("https://cdn.pixabay.com/photo/2017/03/01/16/42/catacombs-2109028_960_720.jpg")
file4 = URI.open("https://cdn.pixabay.com/photo/2017/03/19/13/43/paris-2156511_960_720.jpg")
file5 = URI.open("https://images.unsplash.com/photo-1585944285854-d06c019aaca3?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80")
file6 = URI.open("https://images.unsplash.com/photo-1528535619428-a995242b9096?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80")
file7 = URI.open("https://images.unsplash.com/photo-1526893381913-e311045b8064?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=580&q=80")
file8 = URI.open("https://images.unsplash.com/photo-1624302643140-55f1feead082?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80")
file9 = URI.open("https://images.unsplash.com/photo-1581262177000-8139a463e531?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1315&q=80")
file10 = URI.open("https://images.unsplash.com/photo-1632658443249-f2d8c2abd60c?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80")
file11 = URI.open("https://images.unsplash.com/photo-1614794663647-1b56a77e903b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80")
file12 = URI.open("https://images.unsplash.com/photo-1489348611450-4c0d746d949b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1173&q=80")
file13 = URI.open("https://images.unsplash.com/photo-1513542328669-daa7f8962b01?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80")
file14 = URI.open("https://images.unsplash.com/photo-1520503652613-5a55d772ec77?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80")
file15 = URI.open("https://images.unsplash.com/photo-1495442358998-961b69f45703?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80")
file16 = URI.open("https://images.unsplash.com/photo-1561555804-4b9e0848fdbe?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1974&q=80")
file17 = URI.open("https://cdn.pixabay.com/photo/2014/08/28/14/55/hieroglyphics-429863_1280.jpg")
file18 = URI.open("https://cdn.pixabay.com/photo/2021/06/22/16/39/arch-6356637_1280.jpg")
file19 = URI.open("https://cdn.pixabay.com/photo/2018/03/02/17/19/paris-3193674_1280.jpg")

# offer = Offer.create(price: 35, theme: "Culturel", theme_description: " Decouvrez le mucem autrement!", city: "Marseille", user: user1, title: "Mucem by night", placenumber: 8, description: "Hey ! J'ai 34 ans, je suis passioné par la culture en tout genre mais mon musée préféré reste le mucem ! Il mélange art et architecture ! Mes 2 passions réunis ! J'espère pourvoir vous la transmettre ! A très vite pour une visite")
# offer.photos.attach(io: file, filename: 'mucem.png', content_type: 'image/png')
# offer.photos.attach(io: file2, filename: 'mucem1.png', content_type: 'image/png')
# offer.photos.attach(io: file3, filename: 'mucem2.png', content_type: 'image/png')
# offer2 = Offer.create(price: 20, theme: "Culturel", theme_description: "Decouvrez le mucem", city: "Marseille", user: user2, title: "Mucem", placenumber: 10)
# offer2.photos.attach(io: file4, filename: 'mucem3.png', content_type: 'image/png')
# offer2.photos.attach(io: file5, filename: 'mucem4.png', content_type: 'image/png')
# offer2.photos.attach(io: file6, filename: 'mucem4.png', content_type: 'image/png')
# offer3 = Offer.create(price: 40, theme: "Culturel", theme_description: "Les lieux emblématiques de Marseille", city: "Marseille", user: user3, title: "Les emblèmes Marseillais", placenumber: 12)
# offer3.photos.attach(io: file7, filename: 'ndlg.png', content_type: 'image/png')
# offer3.photos.attach(io: file8, filename: 'ndlg1.png', content_type: 'image/png')
# offer3.photos.attach(io: file9, filename: 'ndlg2.png', content_type: 'image/png')
# offer4 = Offer.create(price: 20, theme: "Culturel", theme_description: "Vivez un match au Vel", city: "Marseille", user: user4, title: "C'est Marseille Bébé", placenumber: 10)
# offer4.photos.attach(io: file10, filename: 'velodrome.png', content_type: 'image/png')
# offer4.photos.attach(io: file11, filename: 'velodrome2.png', content_type: 'image/png')
# offer4.photos.attach(io: file12, filename: 'velodrome3.png', content_type: 'image/png')

offer1 = Offer.create(price: 15, theme: "Mystère", city: "Paris", user: user1, title: "Découvrez les bars cachés !", placenumber: 10)
offer1.photos.attach(io: file, filename: 'bar.png', content_type: 'image/png')
# offer5.photos.attach(io: file11, filename: 'velodrome2.png', content_type: 'image/png')
# offer5.photos.attach(io: file12, filename: 'velodrome3.png', content_type: 'image/png')

offer2 = Offer.create(price: 12, theme: "Mystère", city: "Paris", user: user2, title: "Lieux inaccessible des Catacombes !", placenumber: 10, description: "Salut ! Moi c'est Alex ! J'ai toujours été intéressé par l'histoire de France et de Paris, à tel point que j'ai obtenu un diplôme universitaire en la matière. Après avoir déménagé à Paris il y a de nombreuses années, j'ai commencé à explorer petit à petit les catacombes. Aujourd'hui, je suis devenu expert sur ce lieu. Je passe mes journées à faire des visites dans tout Paris, y compris dans les palais et les musées et à partager l'histoire fascinante de Paris." )
offer2.photos.attach(io: file2, filename: 'catacombes1.png', content_type: 'image/png')
offer2.photos.attach(io: file3, filename: 'catacombes2.png', content_type: 'image/png')
offer2.photos.attach(io: file4, filename: 'catacombes3.png', content_type: 'image/png')



offer3 = Offer.create(price: 8, theme: "Mystère", city: "Paris", user: user3, title: "Découvrez des lieux de tournage !", placenumber: 10)
offer3.photos.attach(io: file5, filename: 'bar.png', content_type: 'image/png')

offer4 = Offer.create(price: 9, theme: "Mystère", city: "Paris", user: user4, title: "Lieux hantés parisien ! ", placenumber: 10)
offer4.photos.attach(io: file6, filename: 'bar.png', content_type: 'image/png')

offer5 = Offer.create(price: 25, theme: "Mystère", city: "Paris", user: user5, title: "Visite nocture à vélo !", placenumber: 10)
offer5.photos.attach(io: file7, filename: 'bar.png', content_type: 'image/png')

offer6 = Offer.create(price: 12, theme: "Mystère", city: "Paris", user: user6, title: "Parisian American Horror Story!", placenumber: 10)
offer6.photos.attach(io: file8, filename: 'bar.png', content_type: 'image/png')

offer7 = Offer.create(price: 13, theme: "Mystère", city: "Paris", user: user7, title: "Paris et ses plus beaux secrets ! ", placenumber: 10)
offer7.photos.attach(io: file9, filename: 'bar.png', content_type: 'image/png')

offer8 = Offer.create(price: 6, theme: "Mystère", city: "Paris", user: user8, title: "Découvrez Paris comme un parisien ! ", placenumber: 10)
offer8.photos.attach(io: file10, filename: 'bar.png', content_type: 'image/png')

offer9 = Offer.create(price: 13, theme: "Mystère", city: "Paris", user: user9, title: "Père Lachaise rites et mystères ! ", placenumber: 10)
offer9.photos.attach(io: file11, filename: 'bar.png', content_type: 'image/png')

offer10 = Offer.create(price: 15, theme: "Mystère", city: "Paris", user: user10, title: "Chasse aux trésors ! ", placenumber: 10, description: "Hey ! 
  Et si on jouait ensemble à découvrir Paris et ses recoins cachés à travers une véritable chasse aux trésors ? 
  En tant qu’habitante de Paris depuis plusieurs années, je vais vous dévoiler de nombreux lieux méconnus et d'autres plus incontournables. 
  C’est parti transformez-vous en Pirate des villes !")
offer10.photos.attach(io: file12, filename: 'bar.png', content_type: 'image/png')
offer10.photos.attach(io: file18, filename: 'catacombes2.png', content_type: 'image/png')
offer10.photos.attach(io: file19, filename: 'catacombes3.png', content_type: 'image/png')

offer11 = Offer.create(price: 12, theme: "Mystère", city: "Paris", user: user11, title: " Retrouvez le bossu de Notre-Dame !", placenumber: 10)
offer11.photos.attach(io: file13, filename: 'bar.png', content_type: 'image/png')

offer12 = Offer.create(price: 18, theme: "Mystère", city: "Paris", user: user12, title: " Jeu de piste !", placenumber: 10)
offer12.photos.attach(io: file14, filename: 'bar.png', content_type: 'image/png')

offer13 = Offer.create(price: 16, theme: "Mystère", city: "Paris", user: user13, title: " Découvrez un Paris inconnu !", placenumber: 10)
offer13.photos.attach(io: file15, filename: 'bar.png', content_type: 'image/png')

offer14 = Offer.create(price: 17, theme: "Mystère", city: "Paris", user: user14, title: " La folle architecture de la destruction !", placenumber: 10)
offer14.photos.attach(io: file16, filename: 'bar.png', content_type: 'image/png')

offer15 = Offer.create(price: 14, theme: "Mystère", city: "Paris", user: user15, title: " Partez à la rencontre de votre histoire !", placenumber: 10)
offer15.photos.attach(io: file17, filename: 'bar.png', content_type: 'image/png')

# offer16 = Offer.create(price: 10, theme: "Mystère", city: "Paris", user: user15, title: " Partez à la rencontre de votre histoire !", placenumber: 10)
# offer16.photos.attach(io: file18, filename: 'bar.png', content_type: 'image/png')

review1 = Review.create(rating: 5, user: user1, offer: offer2, content: "Journée incroyable avec Axel, superbe découverte, je recommande !", visiting_date: "03/01/2022")
review2 = Review.create(rating: 4, user: user3, offer: offer2, content: "Aprem fantastique avec Axel, une activité que je n'aurais jamais faites sans lui, merci !", visiting_date: "12/11/2021")
review3 = Review.create(rating: 4, user: user4, offer: offer2, content: "Axel est super cool et sympa, l'activité est top, foncez !", visiting_date: "17/12/2021")
review4 = Review.create(rating: 5, user: user5, offer: offer2, content: "Le meilleur Halloween que j'ai passé grâce à Axel, encore merci !", visiting_date: "31/10/2012")
review5 = Review.create(rating: 4, user: user6, offer: offer2, content: "Hyper cool, très loin des activités touristiques grâce à un guide au top !", visiting_date: "15/09/2021")
review6 = Review.create(rating: 5, user: user7, offer: offer2, content: "Très bon moment en compagnie d'Axel, merci encore pour cette belle découverte !", visiting_date: "08/08/2021")

